[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "cde0dd4423d2ca4beefa717cd3029162f58c1d50"
os = "macos"

    [[basiclu.download]]
    sha256 = "0d31c60de515fc62d58b6468eb5502386e623ce2c7d563374a25c7b8e4bcfa17"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.aarch64-apple-darwin.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "8ee08adf3a19742959ce08acdd0cba9149c7ae8f"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "b85543ed981446f4537f661c1cda368c12ce5245773352558e233f8ba0c586c7"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.aarch64-linux-gnu.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "5f81b0394f8cbbdec90b36dec9d04f451be67a05"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "900a1a0fc61e5d5b48309ccf06db8f5e4dc604dd55854b9684005cf2cc2cfe9a"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.aarch64-linux-musl.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b32ccd23e273a6db43aeb12cfa4e210556798f9"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "e283a5b10e0fa5828a120866973eee7deecd2905b547f0aea1ef73e3522dc22d"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.armv6l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c4918186890acad98f35e1af3668dd0ac6d0ec0"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "efc2e45861dccb17755a5a67cc8ddfb1bc58bc781b73dfabb4131d8ac9b274fc"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.armv6l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b13d28aae08d8fcb898994f861036470754d6edd"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "f70b9913d5a96658b5e786c64f208199a94fe57422b2adb78c7bb8a583369a78"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b00d54ebebd03e8026e29c1167d16746a448c8e"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "5b1b003b61ef677545f2b6e2e2bb6527dec825fc41318b94f8977afdf44f2fe0"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "0c2ab2a5e378ffb3ef87be63d5cabf1485683473"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "94cd2457f4455bfe4f3c5ac6ae07c6f0c64a10c73609e34e07718dd0ee0576b1"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.i686-linux-gnu.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "14cf25723fc1190b854dd2d0d31d390be1e6d476"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "db53e15fb85cc3b2040b2f46207ea6c3ddad984b85b13070f96bff9f3fda9317"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.i686-linux-musl.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "6b38b9ca714b634db5e68fcdc44c216b68ac320d"
os = "windows"

    [[basiclu.download]]
    sha256 = "311b51a984c5dcd6868312106183d8ec54b5a4a6b0daa1f6c382dd11d1f05885"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.i686-w64-mingw32.tar.gz"
[[basiclu]]
arch = "powerpc64le"
git-tree-sha1 = "0f9d0cd3cb815812d2766599a5047a1e62f7e738"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "87a23d034aa695ac2faecc6d37850badbe0ed4575963b01bc2608515b136f95b"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "38a7bbce7f627a30c4f6d6dc4ef29502175c87a7"
os = "macos"

    [[basiclu.download]]
    sha256 = "68bc440fd5583a5cb3fc24352387f57c35e7fab51455af1f42c6e997a1dc4424"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.x86_64-apple-darwin.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "7b69e0160c2c97b98b3ee11e62b5752f73c7bef9"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "cb3615582db6c504f266b3847e361616365d49a4d0828884bd37efa9ecacd6d6"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.x86_64-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "8ddd13aa00a89391a48b71f4100cdce081f661f4"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "c9f0a65e03b2115ee78ef9b7aa984d1ce6206e23c5742f3293fc6be794aa78bd"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.x86_64-linux-musl.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "0ac9eb7437ade5859b40eec060a0eedec5874896"
os = "freebsd"

    [[basiclu.download]]
    sha256 = "bdb6e3005941be4fdb836f124c5c28928a5ec5c6a7c32d93086518239651054a"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.x86_64-unknown-freebsd.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "eb9d5b142f45bbe5f411d3737c4f560dbbb4f3e5"
os = "windows"

    [[basiclu.download]]
    sha256 = "fd63ed72c88906a86c43ea6eb2f491d4f6f8f4f3026292820456eef205c7f7e5"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+1/basiclu.v2.1.0.x86_64-w64-mingw32.tar.gz"
