[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "328c99075626d1c6fb258e0bc443fa0b05259db5"
os = "macos"

    [[basiclu.download]]
    sha256 = "f4c6c97d20f09e37b35dfaf5b4de74455a8c3aa7a6bc6fca73810bec22d8f59e"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.aarch64-apple-darwin.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "8919f2d4a775074df1db25d13242941f24ea6475"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "2c105422b51a8ba523c84145a171b2201100484c992ddb33f06dc1139b3f8974"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.aarch64-linux-gnu.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "8e8abea055270d3ebdd0d89c707d82e56d679705"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "be5a92e3d2dbf29e4fd39e1ab285195a0c8a476907e720f0e646a01fbf7af5ab"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.aarch64-linux-musl.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc462c049a04cc96a4ad9d1243097c356eb845c1"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "b21914f1e9680beb84666c2cc5c2250b4c6ad3a0734118df64168abb50c13a35"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.armv6l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e29e19880e6145f4f1e9d061a3ceaacad33c44b"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "e5477b9c8545e6e0d62624a256b8f91c78618dd848356065e644ca9c86136151"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.armv6l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43c30030e606ada7ab6b092cd662d86d91dcadb3"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "a2081d120c2aed6cb0a99b8b1d73e07fcca91dcb108276535f1b2b64ed5260ff"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00cf7353a51e72db2e998b2aeaa305b33595e31b"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "e21ce8bcb0d69877f8074c88e2cf13195cbbff85c1d56d37cf6ff4db0a871954"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "6ed36a83980ac64cc4cab35dc6f7ea4dbc2e03c2"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "dadd207d764f71cef27db8bde52eccf2074e4cdf3abbbe2912bc181ede1d0e78"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.i686-linux-gnu.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "85e505cf4d62a539a85a9134ba19158a1b98c6e2"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "a07125e5cec58db606cfe360be4be3c1e7cf551d8e3d27da3b72a5282db64194"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.i686-linux-musl.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "183dce87f50f28871bebd2d2a57bbfb53f1bec23"
os = "windows"

    [[basiclu.download]]
    sha256 = "8a56b171f7339d1a5ff7cfef0f4819169da1f5d33f0ec734316b8ce237715d15"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.i686-w64-mingw32.tar.gz"
[[basiclu]]
arch = "powerpc64le"
git-tree-sha1 = "0303f114e9fa755b80eb64d650a133b41f159465"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "14abbfd9486a11e629a974e1f9b32a03182b5e835e8d57575002226a1c3021dd"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "d46a50c1b296d810678755aff7c3706ccb87518e"
os = "macos"

    [[basiclu.download]]
    sha256 = "7a4a412e4f9a26b6e7e1c46e4a081393ef80215ff25557401524c601ffd27f18"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.x86_64-apple-darwin.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "39bc5cc92c6a32e45b4f1f9935405c080ea40fbf"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "1f3d992a1df40b477c14347fec62ab76ddcc71a58bd8e593306e0362edda8bb8"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.x86_64-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "2c907785ba3164250b4597047ffdedab471e8f22"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "bb10798876037b2b05fb6b49644e19380cc5b1474ca14909987f7a4b24c43ade"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.x86_64-linux-musl.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "b44376b071772ad62c766a9301b8ed89e925653f"
os = "freebsd"

    [[basiclu.download]]
    sha256 = "99719af5a17313f619d3c2a7c35f7595a82177b5aa813520a7f9efee81453ed5"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "ba19c9026e63f5699fdc022abb526d6a54e0802b"
os = "windows"

    [[basiclu.download]]
    sha256 = "9608dfb605c75793fceb09a21581978da430fcd93be3914adbd163bc603aef16"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.2.0+0/basiclu.v2.2.0.x86_64-w64-mingw32.tar.gz"
