[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "ba4e8c663cc111461e76134c85ae6bfed8c68df7"
os = "macos"

    [[basiclu.download]]
    sha256 = "eadde7f21e44f46a8f62e6a8ea89676ba6df8592599546fd8278ec95c1f09b98"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.aarch64-apple-darwin.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "46f6b0f58e635e24d60d640931fe31044bfea99e"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "8fce2c98ba1a59936424a19fa62e89364e28b6fe5067261144556398ad799656"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.aarch64-linux-gnu.tar.gz"
[[basiclu]]
arch = "aarch64"
git-tree-sha1 = "94d474ecef94a9bfc87d40dc379f9fe6c1b7c611"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "15e50661b3071574dc5320e25ccd4a5e4caa65c4ae71db4c6956cf2a4db760cc"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.aarch64-linux-musl.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e15558bc99d156956a4cb622ee9d578a07c67e6"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "1fabcdefb8a079e66affbca0fe14a39a009eb23fbd75ae400891d8af2679753b"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.armv6l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccd44dc286f5e63ed00f453bb2ec5f23831ed64d"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "7e6e3fb4423edb6fc0e7fb466854e930e5ac20c97977bd9b152836dae94c019d"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.armv6l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a64292697f2cd842aa0883914f9b652c83cb094"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "9d296e6f7d1ea563bad4760ab412f71e01899793cbd84e5d8e386265ef262b1f"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[basiclu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6958545e8325dcfab205791cee731fa19d708e4"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "9f7fcb16a53d113adb18cfad30377c56c9ae83ee78517972f8be847fc3be7855"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "b5c89fee9865d23fce5594b5e5563c8a522f0a41"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "d381bfbc11012fe470d48f6f51a19f4a912bad946e84ffd333e4f782abb2f73a"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.i686-linux-gnu.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "6f3b5db792a17637dd1762b7217111d6e5a485f7"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "331d01106be397ae41ce13f43f405b264a765e19647befd8ebb04de80c01729d"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.i686-linux-musl.tar.gz"
[[basiclu]]
arch = "i686"
git-tree-sha1 = "f96f2ec6286f925ec59b74cabb0dc398a9389ab0"
os = "windows"

    [[basiclu.download]]
    sha256 = "5466b05b27f2c6a61176d9b62393520085413d41691572c75702d73ab28d730f"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.i686-w64-mingw32.tar.gz"
[[basiclu]]
arch = "powerpc64le"
git-tree-sha1 = "49cb1ca5ff30bf77ea4afa7a8b4dd8020549d3ff"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "0b40582fe0fdada93edfbc7ee64ca757f45bc5b1622fb58c4f4cf194944539e4"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "573a5dc85d37efe0a1ed6524cdea364314a5d772"
os = "macos"

    [[basiclu.download]]
    sha256 = "33782424adee8ad347fe009918e6476cfcff4a078140d02cc2552f50e6cbf09f"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.x86_64-apple-darwin.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "8bbd135edf4a60b9a806cbadb563145cf38df649"
libc = "glibc"
os = "linux"

    [[basiclu.download]]
    sha256 = "ede601141f8758704687f0c12c7b21b2421af75577e5b39da47b4fd08ad7713c"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.x86_64-linux-gnu.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "93b862147ae18fd8e1d2a641c79d7ffdbf867d81"
libc = "musl"
os = "linux"

    [[basiclu.download]]
    sha256 = "24d57d12bab41bb8bd9f41f28eb8f837af08d8947d45eeacc1ef874beb245d4d"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.x86_64-linux-musl.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "76bd26fc99c67bf6cb89cf69268c53f686fd1476"
os = "freebsd"

    [[basiclu.download]]
    sha256 = "005c816b5a0d744c0f14be2f147ddc9d7cd47a17ab106eb0fb7f0408ec4b2c54"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.x86_64-unknown-freebsd.tar.gz"
[[basiclu]]
arch = "x86_64"
git-tree-sha1 = "d29e2a90d5b7a751125787f8812c57927851dabb"
os = "windows"

    [[basiclu.download]]
    sha256 = "cfd0f915efb4dd82dcfb346c437b8b871d954a984051d207da63951b4d47d9cf"
    url = "https://github.com/JuliaBinaryWrappers/basiclu_jll.jl/releases/download/basiclu-v2.1.0+2/basiclu.v2.1.0.x86_64-w64-mingw32.tar.gz"
