# Autogenerated wrapper script for basiclu_jll for aarch64-apple-darwin
export libbasiclu

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("basiclu")
JLLWrappers.@declare_library_product(libbasiclu, "@rpath/libbasiclu.2.1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libbasiclu,
        "lib/libbasiclu.2.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
