# Autogenerated wrapper script for basiclu_jll for i686-w64-mingw32
export libbasiclu

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("basiclu")
JLLWrappers.@declare_library_product(libbasiclu, "libbasiclu.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libbasiclu,
        "bin\\libbasiclu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
